# Generated by Django 5.1.7 on 2025-04-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_method_name',
            field=models.CharField(max_length=255),
        ),
    ]
