# Generated by Django 5.1.7 on 2025-04-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions_App', '0002_alter_paymentmethod_payment_method_name'),
        ('userModule_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('user', 'payment_method_name')},
        ),
    ]
