# Generated by Django 5.1.7 on 2025-04-06 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions_App', '0003_alter_paymentmethod_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylater',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paylater_transaction', to='Transactions_App.transaction'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_transaction', to='Transactions_App.transaction'),
        ),
    ]
