# Generated by Django 5.1.7 on 2025-04-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions_App', '0005_alter_category_options_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
