# Generated by Django 5.1.7 on 2025-04-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions_App', '0006_category_visible_paymentmethod_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('refunded', 'Refunded')], max_length=10),
        ),
    ]
