# Generated by Django 5.1.7 on 2025-04-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions_App', '0006_category_visible_paymentmethod_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expense_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('refund', 'Refund'), ('paylater', 'Pay Later'), ('refunded', 'Refunded')], default='normal', max_length=10),
        ),
    ]
