# Generated by Django 5.1.7 on 2025-04-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions_App', '0007_alter_transaction_expense_type'),
        ('Transactions_App', '0007_alter_transaction_type'),
    ]

    operations = [
    ]
