# Generated by Django 5.1.7 on 2025-04-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions_App', '0008_merge_20250427_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expense_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('refund', 'Refund'), ('paylater', 'Pay Later')], default='normal', max_length=10),
        ),
    ]
